[workspace]
members = [ "src/error","src/lexer" , "src/parser"]

[package]
name = "ion"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "src/lexer" }
parser = { path = "src/parser" }
